#!/usr/bin/env bash
# print domains and subdomains

print_domain_subdomain () {
    local domain="$1"
    local subdomain="$2"
    local record_type="A"
    local destination

    destination=$(dig "$subdomain.$domain" | awk '/^'"$subdomain"'/ {print $NF}')

    # Print the result
    echo "The subdomain $subdomain is a $record_type record and points to $destination"
}

if [ "$#" -eq 1 ]; then
    print_domain_subdomain "$1" "www"
    print_domain_subdomain "$1" "lb-01"
    print_domain_subdomain "$1" "web-01"
    print_domain_subdomain "$1" "web-02"
elif [ "$#" -eq 2 ]; then
    print_domain_subdomain "$1" "$2"
else
    echo "Usage: $0 <domain> [subdomain]"
    exit 1
fi
